openapi: 3.1.0
info:
  title: Conversation API
  description: API for managing website builder conversations and chat interactions
  version: 1.0.0

servers:
  - url: /api
    description: Application API routes

paths:
  /chat:
    post:
      operationId: streamChat
      summary: Stream a chat message response
      description: |
        Sends a user message and streams an AI response. Uses OpenRouter for model access
        (GPT-4o/Claude for orchestration, GPT-4o-mini for content extraction). Models can be
        switched via configuration without code changes.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Streaming text response
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-Sent Events stream with AI response chunks
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /conversation:
    post:
      operationId: createConversation
      summary: Start a new conversation
      description: Creates a new website building conversation session
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                industry:
                  $ref: '#/components/schemas/IndustryType'
      responses:
        '201':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /conversation/{conversationId}:
    get:
      operationId: getConversation
      summary: Get conversation details
      description: Retrieves full conversation state including messages and business profile
      parameters:
        - $ref: '#/components/parameters/ConversationId'
      responses:
        '200':
          description: Conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

    patch:
      operationId: updateConversation
      summary: Update conversation state
      description: Updates conversation step, business profile, or other state
      parameters:
        - $ref: '#/components/parameters/ConversationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversationUpdate'
      responses:
        '200':
          description: Conversation updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      operationId: deleteConversation
      summary: Delete a conversation
      description: Permanently deletes a conversation and associated data
      parameters:
        - $ref: '#/components/parameters/ConversationId'
      responses:
        '204':
          description: Conversation deleted
        '404':
          $ref: '#/components/responses/NotFound'

  /conversation/{conversationId}/extract:
    post:
      operationId: extractContent
      summary: Extract structured content from user message
      description: |
        Uses AI via OpenRouter (GPT-4o-mini by default) to extract structured section content from natural language.
        Returns validated content matching the section's Zod schema.
      parameters:
        - $ref: '#/components/parameters/ConversationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtractionRequest'
      responses:
        '200':
          description: Extracted content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          description: Extraction failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractionError'

components:
  parameters:
    ConversationId:
      name: conversationId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    IndustryType:
      type: string
      enum: [service, local]

    ConversationStep:
      type: string
      enum:
        - industry_selection
        - business_profile
        - hero
        - services
        - menu
        - about
        - process
        - portfolio
        - testimonials
        - location
        - gallery
        - contact
        - review
        - complete

    Message:
      type: object
      required: [id, role, content, timestamp]
      properties:
        id:
          type: string
        role:
          type: string
          enum: [user, assistant, system]
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        metadata:
          type: object
          properties:
            step:
              $ref: '#/components/schemas/ConversationStep'
            extractedContent:
              type: object

    BusinessProfile:
      type: object
      required: [name, industry, businessType, tagline, description, brandPersonality, contact]
      properties:
        name:
          type: string
          maxLength: 100
        industry:
          $ref: '#/components/schemas/IndustryType'
        businessType:
          type: string
        tagline:
          type: string
          maxLength: 200
        description:
          type: string
          maxLength: 2000
        brandPersonality:
          type: array
          items:
            type: string
          minItems: 1
        colors:
          type: object
          properties:
            primary:
              type: string
              pattern: '^#[0-9A-Fa-f]{6}$'
            secondary:
              type: string
              pattern: '^#[0-9A-Fa-f]{6}$'
            accent:
              type: string
              pattern: '^#[0-9A-Fa-f]{6}$'
        contact:
          type: object
          required: [email]
          properties:
            phone:
              type: string
            email:
              type: string
              format: email
            address:
              type: string

    ChatRequest:
      type: object
      required: [conversationId, message]
      properties:
        conversationId:
          type: string
          format: uuid
        message:
          type: string
          minLength: 1
          maxLength: 5000

    ConversationResponse:
      type: object
      required: [id, currentStep, messages, createdAt, updatedAt]
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
          nullable: true
        industry:
          $ref: '#/components/schemas/IndustryType'
        currentStep:
          $ref: '#/components/schemas/ConversationStep'
        businessProfile:
          $ref: '#/components/schemas/BusinessProfile'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ConversationUpdate:
      type: object
      properties:
        industry:
          $ref: '#/components/schemas/IndustryType'
        currentStep:
          $ref: '#/components/schemas/ConversationStep'
        businessProfile:
          $ref: '#/components/schemas/BusinessProfile'

    ExtractionRequest:
      type: object
      required: [sectionType, userMessage]
      properties:
        sectionType:
          type: string
        userMessage:
          type: string
          maxLength: 5000

    ExtractionResponse:
      type: object
      required: [success, content]
      properties:
        success:
          type: boolean
        content:
          type: object
          description: Validated section content matching the section schema
        confidence:
          type: number
          minimum: 0
          maximum: 1

    ExtractionError:
      type: object
      required: [success, error, rawInput]
      properties:
        success:
          type: boolean
          const: false
        error:
          type: string
        rawInput:
          type: string
        suggestedFields:
          type: object
          description: Partially extracted fields for manual completion

    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
