openapi: 3.1.0
info:
  title: Launch API
  description: API for handling site launch requests and consultant handoff workflow
  version: 1.0.0

servers:
  - url: /api
    description: Application API routes

paths:
  /launch:
    post:
      operationId: submitLaunchRequest
      summary: Submit launch request
      description: |
        Submits a launch request for a completed site. Triggers email confirmation
        to user and notification to consultant team. Requires payment for non-free tiers.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchRequest'
      responses:
        '200':
          description: Launch request submitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '402':
          description: Payment required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequiredError'
        '404':
          $ref: '#/components/responses/NotFound'

  /launch/{launchId}:
    get:
      operationId: getLaunchStatus
      summary: Get launch request status
      description: Retrieves current status of a launch request
      parameters:
        - $ref: '#/components/parameters/LaunchId'
      responses:
        '200':
          description: Launch status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /admin/launches:
    get:
      operationId: listPendingLaunches
      summary: List pending launch requests (Admin)
      description: Returns all sites awaiting launch for consultant review
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [awaiting_launch, in_progress, launched]
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of pending launches
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Admin access required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /admin/launches/{launchId}/status:
    patch:
      operationId: updateLaunchStatus
      summary: Update launch status (Admin)
      description: Updates launch status and optionally adds notes
      parameters:
        - $ref: '#/components/parameters/LaunchId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLaunchStatusRequest'
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchStatusResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Admin access required
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    LaunchId:
      name: launchId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    LaunchRequest:
      type: object
      required: [siteId, preferences]
      properties:
        siteId:
          type: string
          format: uuid
        preferences:
          $ref: '#/components/schemas/LaunchPreferences'

    LaunchPreferences:
      type: object
      required: [email, imagePreference, domainPreference, timeline]
      properties:
        email:
          type: string
          format: email
          description: User email for launch communications
        phone:
          type: string
          description: Optional phone for urgent contact
        imagePreference:
          type: string
          enum: [placeholders, provide_own, need_photography]
          description: |
            - placeholders: Keep placeholder images
            - provide_own: User will provide custom images
            - need_photography: User needs photography services
        domainPreference:
          type: string
          enum: [buy_new, use_existing, hosted_subdomain]
          description: |
            - buy_new: User wants to purchase a new domain
            - use_existing: User has a domain to connect
            - hosted_subdomain: Use platform subdomain (yoursite.builderapp.com)
        existingDomain:
          type: string
          description: Domain name if using existing
          example: mybusiness.com
        timeline:
          type: string
          enum: [asap, this_week, this_month, no_rush]
          description: Desired launch timeline
        notes:
          type: string
          maxLength: 1000
          description: Additional instructions or questions

    LaunchResponse:
      type: object
      required: [launchId, siteId, status, submittedAt, confirmationSent]
      properties:
        launchId:
          type: string
          format: uuid
        siteId:
          type: string
          format: uuid
        status:
          type: string
          enum: [awaiting_launch]
        submittedAt:
          type: string
          format: date-time
        confirmationSent:
          type: boolean
          description: Whether user confirmation email was sent
        estimatedContactTime:
          type: string
          description: When user can expect to be contacted
          example: "Within 24 hours"

    LaunchStatusResponse:
      type: object
      required: [launchId, siteId, status, submittedAt]
      properties:
        launchId:
          type: string
          format: uuid
        siteId:
          type: string
          format: uuid
        status:
          type: string
          enum: [awaiting_launch, in_progress, launched]
        submittedAt:
          type: string
          format: date-time
        preferences:
          $ref: '#/components/schemas/LaunchPreferences'
        assignedConsultant:
          type: string
          description: Name of assigned consultant (admin only)
        consultantNotes:
          type: string
          description: Internal notes (admin only)
        launchedAt:
          type: string
          format: date-time
        deployedUrl:
          type: string
          format: uri
          description: Final deployed URL after launch

    LaunchListResponse:
      type: object
      required: [launches, total, limit, offset]
      properties:
        launches:
          type: array
          items:
            $ref: '#/components/schemas/LaunchListItem'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    LaunchListItem:
      type: object
      required: [launchId, siteId, businessName, status, submittedAt, timeline]
      properties:
        launchId:
          type: string
          format: uuid
        siteId:
          type: string
          format: uuid
        businessName:
          type: string
        industry:
          type: string
          enum: [service, local]
        status:
          type: string
          enum: [awaiting_launch, in_progress, launched]
        submittedAt:
          type: string
          format: date-time
        timeline:
          type: string
          enum: [asap, this_week, this_month, no_rush]
        previewUrl:
          type: string
          format: uri
        userEmail:
          type: string
          format: email

    UpdateLaunchStatusRequest:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [awaiting_launch, in_progress, launched]
        consultantNotes:
          type: string
          maxLength: 2000
        deployedUrl:
          type: string
          format: uri
          description: Required when marking as launched

    PaymentRequiredError:
      type: object
      required: [code, message, pricing]
      properties:
        code:
          type: string
          const: PAYMENT_REQUIRED
        message:
          type: string
          example: "Export and launch require payment"
        pricing:
          type: object
          properties:
            starterPrice:
              type: integer
              example: 99
            proPrice:
              type: integer
              example: 299
            currency:
              type: string
              example: USD

    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
